### ISSUE TITLE
Some method descriptions/property attributes in headerfiles missing

### ISSUE THREAD

**Issue by trailblazr** [RossAnderson/EarthView#2]
Hi Ross,

I just downloaded the project and tried to compile it unter SDK iOS 5. It revealed some missing entries in headerfiles for me.

Following classes needed changes to make it run for me (I added the method descriptions/property attribs to .h file):

RAManipulator.h
- (void)updateCamera;
- (void)stop:(id)sender;

RAPage.h
@property (readonly, retain, nonatomic) NSString \* key;

RARenderVisitor.h
- (void)traversePage:(RAPage *)page withModelViewProjectionMatrix:(GLKMatrix4)matrix;

RASceneGraphController.h
- (void)setupSceneObjects;
- (RANode *)createSceneGraphForPager:(RATilePager *)pager;
- (void)update;

RAShaderProgram.h
- (BOOL)compileShader:(GLuint *)shader type:(GLenum)type file:(NSString *)file;
- (BOOL)validateProgram:(GLuint)prog;

RATilePager.h
@property (readonly, retain) NSSet \* rootPages;
- (RAPage *)makeLeafPageForTile:(TileID)t withParent:(RAPage *)parent;
- (void)traverse;

RAWorldTour.h
- (void)next:(id)sender;

hope this helps somehow.

Perhaps try a clean build to reveal these builderrors, e.g. press ALT-key while in Xcode menu "Product" and select "Clean build folder..." this might reveal the issue on your machine.

regards,
Helge

**Comment by RossAnderson** [comment]
The methods listed are private for those classes and should not be listed in the header (which is the public interface to the class). Not defining these methods is completely legal with Xcode 4.3, however older versions that use GCC instead of LLVM will have those errors.

To resolve the issue for you, I have added private method declarations into the implementation file. Let me know if there are still issues. Thanks for reporting this.
